echo "We are trying this practical from linux EC2"
echo "I am from Young minds"
echo "We are from batch-27 and learning DevOps"
echo "I am working in REQ092348"
echo "I have learnt Github and Git"
echo "This is my verison 1.1.123"
echo "Jenkis Pole SCM is successfully tested"
echo "also varifed the Jenkinsfile"
echo "This is my verison 1.1.123"